# Generated by Django 2.1.5 on 2019-08-27 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='picture',
            new_name='car_img',
        ),
    ]
